[phases.setup]
nixPkgs = [
  'nodejs-18_x',
  'npm-8_x',
  'chromium',
  'nss',
  'freetype',
  'fontconfig',
  'libx11',
  'libxcomposite',
  'libxdamage',
  'libxrandr',
  'libgbm',
  'libxss',
  'libasound'
]

[phases.install]
cmds = ['npm ci --omit=dev']

[phases.build]
cmds = []

[start]
cmd = 'node glamira_scraper.js'

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = 'false'
NODE_ENV = 'production'
