# nixpacks.toml

[phases.setup]
nixPkgs = [
  "nodejs-18_x",
  "chromium",
  "nss",
  "freetype",
  "harfbuzz",
  "ca-certificates",
  "ttf-freefont",
  "fontconfig"
]
cmds = ["npm ci --only=production"]

[phases.build]
# No extra build steps—use system Chromium
cmds = []

[variables]
# Tell Puppeteer to use system Chromium and skip its download
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "chromium"
NODE_ENV = "production"

[start]
cmd = "node glamira_scraper.js"
