[phases.setup]
nixPkgs = [
  "chromium",
  "cacert",
  "glib",
  "nss",
  "nspr",
  "atk",
  "at-spi2-atk",
  "libdrm",
  "libxkbcommon",
  "libxcomposite",
  "libxdamage",
  "libxrandr",
  "libgbm",
  "alsa-lib",
  "pango",
  "cairo",
  "at-spi2-core",
  "gtk3",
  "gdk-pixbuf"
]

[phases.install]
cmds = [
  "npm ci --only=production"
]

[phases.build]
cmds = [
  "echo 'Build completed'"
]

[start]
cmd = "npm start" 