[phases.setup]
nixPkgs = [
  "chromium",
  "cacert"
]

[phases.install]
cmds = [
  "npm ci --only=production"
]

[phases.build]
cmds = [
  "echo 'Build completed'"
]

[start]
cmd = "npm start" 