[phases.setup]
nixPkgs = [
  "chromium",
  "ca-certificates",
  "glib",
  "nss",
  "nspr",
  "atk",
  "at-spi2-atk",
  "libdrm",
  "libxkbcommon",
  "libxcomposite",
  "libxdamage",
  "libxrandr",
  "libgbm",
  "libasound",
  "libpango-1.0",
  "libcairo2",
  "libatspi",
  "libgtk-3",
  "libgdk-pixbuf-2.0"
]

[phases.install]
cmds = [
  "npm ci --only=production"
]

[phases.build]
cmds = [
  "echo 'Build completed'"
]

[start]
cmd = "npm start" 